"""empty message

Revision ID: 19dd1fd94ca0
Revises: 6cc5a4f3d33c
Create Date: 2019-12-27 14:07:39.445633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dd1fd94ca0'
down_revision = '6cc5a4f3d33c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employee_name', table_name='employee')
    op.create_index(op.f('ix_employee_name'), 'employee', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_name'), table_name='employee')
    op.create_index('ix_employee_name', 'employee', ['name'], unique=True)
    # ### end Alembic commands ###
