"""empty message

Revision ID: 1abef5adae21
Revises: 
Create Date: 2019-11-27 15:25:06.630098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abef5adae21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_email'), 'test', ['email'], unique=True)
    op.create_index(op.f('ix_test_username'), 'test', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_username'), table_name='test')
    op.drop_index(op.f('ix_test_email'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
