"""empty message

Revision ID: 35d84fb87e0d
Revises: 768fb6dfabab
Create Date: 2019-11-27 18:25:48.645409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d84fb87e0d'
down_revision = '768fb6dfabab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('claim', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('employee', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('employee', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('file', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'created_at')
    op.drop_column('employee', 'updated_at')
    op.drop_column('employee', 'created_at')
    op.drop_column('claim', 'updated_at')
    op.drop_column('claim', 'created_at')
    # ### end Alembic commands ###
