"""empty message

Revision ID: 768fb6dfabab
Revises: 9bfcb8c3a8d9
Create Date: 2019-11-27 18:19:12.388467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768fb6dfabab'
down_revision = '9bfcb8c3a8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('team', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_index(op.f('ix_employee_name'), 'employee', ['name'], unique=True)
    op.create_index(op.f('ix_employee_team'), 'employee', ['team'], unique=False)
    op.create_table('claim',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=64), nullable=True),
    sa.Column('emp_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_team'), 'claim', ['team'], unique=False)
    op.create_table('file',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('claim_id', sa.String(length=64), nullable=True),
    sa.Column('emp_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_name'), 'file', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_name'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_claim_team'), table_name='claim')
    op.drop_table('claim')
    op.drop_index(op.f('ix_employee_team'), table_name='employee')
    op.drop_index(op.f('ix_employee_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
