"""empty message

Revision ID: 9c791a5e2c56
Revises: b2476c1eb834
Create Date: 2019-12-19 10:40:18.690802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c791a5e2c56'
down_revision = 'b2476c1eb834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('password', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'password')
    # ### end Alembic commands ###
