"""empty message

Revision ID: ee30881b21b9
Revises: 19dd1fd94ca0
Create Date: 2020-01-03 17:40:48.475564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee30881b21b9'
down_revision = '19dd1fd94ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('teams', sa.ARRAY(sa.String()), nullable=True))
    op.create_index(op.f('ix_employee_teams'), 'employee', ['teams'], unique=False)
    op.drop_index('ix_employee_team', table_name='employee')
    op.drop_column('employee', 'team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('team', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_employee_team', 'employee', ['team'], unique=False)
    op.drop_index(op.f('ix_employee_teams'), table_name='employee')
    op.drop_column('employee', 'teams')
    # ### end Alembic commands ###
