from app.routes.employee import create_employee
from app.routes.employee import delete_employee
from app.routes.auth import verify_password
from app.routes.auth import get_auth_token
from app.routes.role import create_role
from app.routes.role import delete_role
from app.routes.index import index
from app.routes.team import get_all_teams
from app.routes.claim import create_claim
from app.routes.claim import approve_claim